### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/picl-keyserver#16]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- the wiki has been disabled, as it was not used

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by vladikoff** [comment]
@rfk let's archive this repo as well

**Comment by rfk** [comment]
I appear to have given up my admin privileged here, but I agree with archiving this.  @moz-hwine please help? :-)

**Comment by ghost** [comment]
archived
